# Archivo: monitoring/prometheus/prometheus.yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  
  - job_name: "product-service"
    metrics_path: '/metrics'
    scrape_interval: 30s   # Debe ser mayor que el timeout
    scrape_timeout: 20s    # Debe ser menor que el intervalo
    static_configs:
      - targets: ["product-service:3001"]
  
  - job_name: "inventory-service"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["inventory-service:3002"]